---
title: "PDF Scraping WA Covid Data using OneDrive"
output: 
  html_document:
    keep_md: true
editor_options: 
  chunk_output_type: console
---

# Setup

Load packages and setup a data folder in OneDrive, assuming you have already configured OneDrive sync client using the defaults.

```{r}
# Load packages
if (!require(pacman)) install.packages("pacman")
pacman::p_load(readr, dplyr, httr, tabulizer)

# Construct data folder path
onedrive_path <- ifelse(Sys.getenv('OneDrive') != "", Sys.getenv('OneDrive'), 
  file.path(gsub('[\\/]+Documents', '', Sys.getenv('HOME')), 'OneDrive'))
data_dir <- file.path(onedrive_path, 'coders', 'data')

# Create data folder if it does not already exist
if (!dir.exists(data_dir)) {
  dir.create(data_dir, showWarnings = FALSE, recursive = TRUE)
}
```

# Get PDF File

See: https://www.doh.wa.gov/Emergencies/COVID19/DataDashboard#downloads

```{r}
# Download file
filename <- "Weekly-COVID-19-Long-Term-Care-Report.pdf"
filepath <- file.path(data_dir, filename)
if (!file.exists(filepath)) {
  url <- paste0('https://www.doh.wa.gov/Portals/1/Documents/1600/coronavirus/',
                'data-tables/', filename)
  response_msg <- GET(url, write_disk(filepath, overwrite = TRUE))
}
```

# Extract Data from PDF File

```{r}
txt <- extract_text(file = filepath)
lines <- read_lines(txt)
lines <- c('county;deaths;cases', 
           grep('^[A-Z].*[0-9,]+\\s+[0-9,]+\\s*$', lines, value = TRUE))
lines <- gsub('\\s+(\\d)', ';\\1', lines) %>% gsub(',', '', .)
df <- read_delim(lines, delim = ';', trim_ws = TRUE)
```

# View Data

```{r}
knitr::kable(df)
```
